version: "3.1"

services:
  postgres:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: mist
      POSTGRES_DB: mist_wallet
      POSTGRES_PASSWORD: 123
    ports:
      - "5434:5432"
