version: "3.1"

services:
  postgres:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: mist
      POSTGRES_DB: mist_wallet
      POSTGRES_PASSWORD: 123
  wallet:
    image: "mist_wallet"
    restart: always
    ports:
      - "9999:9999"
    environment:
      WAIT_HOSTS: postgres:5432
